---

- name: Play for maser hots
  hosts: master
  become: true
  become_user: root
  tasks:

  # Install Docker and its dependent components.
  - name: Install packages that allow apt to be used over HTTPS
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

  - name: Add an apt signing key for Docker
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version of docker
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Install docker and its dependecies
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    notify:
      - Docker status

  - name: Add ubuntu user to docker group
    ansible.builtin.user:
      name: ubuntu
      group: docker

  - name: Create docker daemon json config file
    ansible.builtin.lineinfile:
      path: /etc/docker/daemon.json
      line: "{{ item }}"
      create: true
      mode: 0666
    with_items:
      - '{'
      - '   "exec-opts": ["native.cgroupdriver=systemd"],'
      - '   "log-driver": "json-file", '
      - '   "log-opts":{'
      - '   "max-size": "100m"'
      - '    },'
      - '   "storage-driver": "overlay2"'
      - '}'

  - name: Restart docker
    ansible.builtin.service:
      name: docker
      enabled: true
      daemon_reload: true
      state: restarted

    # Kubelet will not start if the system has swap enabled, so we are disabling swap using the below code
  - name: Remove swapfile from /etc/fstab
    ansible.posix.mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    ansible.builtin.command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Set bridge-nf-call settings
    ansible.builtin.command: "{{ item }}"
    with_items:
      - modprobe overlay
      - modprobe bridge
      - modprobe br_netfilter
    register: my_output # <- Registers the command output.
    changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.

  - name: Configure sysctl
    ansible.builtin.lineinfile:
      path: /etc/sysctl.d/kubernetes.conf
      line: "{{ item }}"
      create: true
      mode: 0666
    with_items:
      - 'net.bridge.bridge-nf-call-iptables = 1'
      - 'net.bridge.bridge-nf-call-ip6tables = 1'
      - 'net.ipv4.ip_forward = 1'


  - name: Restart sysctl
    ansible.builtin.command: sudo sysctl --system
    register: my_output # <- Registers the command output.
    changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.

  # Installing kubelet, kubeadm and kubectl using the below code
  - name: Add an apt signing key for Kubernetes
    ansible.builtin.apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64] https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: present
      update_cache: true
    vars:
      packages:
        - kubelet
        - kubeadm
        - kubectl
        - kubernetes-cni

  - name: Setting hostname
    ansible.builtin.command: hostnamectl set-hostname k8s-master
    register: my_output # <- Registers the command output.
    changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.

  - name: Restart kubelet
    ansible.builtin.service:
      name: kubelet
      daemon_reload: true
      enabled: true
      state: restarted

# because this was hapened "code = Unimplemented desc = unknown service runtime.v1alpha2.ImageService"
# https://github.com/containerd/containerd/issues/4581
  - name: Delete config.toml
    ansible.builtin.file:
      path: /etc/containerd/config.toml
      state: absent

  - name: Restart the containerd service
    ansible.builtin.service:
      name: containerd
      daemon_reload: true
      enabled: true
      state: restarted

  - name: Pull container images
    ansible.builtin.command: kubeadm config images pull
    register: my_output # <- Registers the command output.
    changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.
    tags: k8s_init

  - name: Reset exist Kubernetes cluster
    ansible.builtin.command: kubeadm reset --force
    register: my_output # <- Registers the command output.
    changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.
    tags: k8s_init

    # Initialize the Kubernetes cluster with kubeadm using the below code
  - name: Initialize the Kubernetes cluster using kubeadm
    ansible.builtin.command: kubeadm init --pod-network-cidr=10.244.0.0/16 --upload-certs --node-name k8s-master --control-plane-endpoint={{ ansible_host }}
    register: my_output # <- Registers the command output.
    changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.
    tags: k8s_init

    # Setup the kube config file for the 'ubuuntu' user to access the Kubernetes cluster using the code below
  - name: Setup kubeconfig for ubuntu user (create dir)
    ansible.builtin.file:
      path: /home/ubuntu/.kube
      state: directory
      owner: ubuntu
      mode: 0777
    tags: k8s_init

  - name: Setup kubeconfig for ubuntu user (copy config to remote directory)
    ansible.builtin.copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/ubuntu/.kube/config
      owner: ubuntu
      mode: 0666
      remote_src: true
    tags: k8s_init

    # Setup the container networking provider
  - name: Install flannel
    become: false
    ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    register: my_output # <- Registers the command output.
    changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.
    tags: k8s_init

  # Generate kube join command for joining the node to the Kubernetes cluster and store the command in the file named join-command
  - name: Generate join command
    ansible.builtin.command: kubeadm token create --print-join-command
    register: join_command
    changed_when: join_command.rc != 0
    tags: k8s_init

  - name: Copy join command to local file
    become: false
    ansible.builtin.copy:
      content:
        "{{ join_command.stdout_lines[0] }}"
      dest: ./join-command
      mode: 0666
    delegate_to: localhost

    # register: my_output # <- Registers the command output.
    # changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.
    tags: k8s_init

  - name: Copy config file
    ansible.builtin.fetch:
      src: /etc/kubernetes/admin.conf
      dest: "{{ lookup('env', 'HOME') }}/.kube/config"
      flat: true
    # run_once: true
    ignore_errors: "{{ ansible_check_mode }}" # <- Ignores errors in check mode.
    tags: k8s_init

  # Setup a handler for checking Docker daemon using the below code.
  handlers:
    - name: Docker status
      ansible.builtin.service:
        name: docker
        state: started
